apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/redirect-entry-point: https
    ingress.kubernetes.io/whitelist-x-forwarded-for: "true"
  labels:
    igou-app: website
  name: igou-website-ingress
  namespace: igou
spec:
  rules:
  - host: igou.io
    http:
      paths:
      - backend:
          serviceName: igou-website
          servicePort: 80
  - host: www.igou.io
    http:
      paths:
      - backend:
          serviceName: igou-website
          servicePort: 80
  tls:
  - hosts:
    - igou.io
    - www.igou.io
    secretName: igou-blog-acme-certificate
