# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Igou
email: igou.david@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Igou
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /blog/:year:month:day-:title/
url: "https://igou.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: igou
github_username:  david-igou


plainwhite:
  name: David Igou
  tagline: Container Infrastructure Consultant
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  social_links:
    github:  david-igou


# Build settings
markdown: kramdown
theme: plainwhite
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-code-tabs

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - do_it_live.sh
  - Dockerfile
